baseURL = 'https://yw-choi.github.io'
title = 'YOUNG WOO CHOI'
theme = 'ywchoi'
languageCode = 'en-US'
enableRobotsTXT = true

[params]
google_analytics_tag = "G-4VEF9JDEXP"
description = "Computational Quantum Materials Physics Lab at Sogang University"

[sitemap]
changefreq = 'monthly'
filename = 'sitemap.xml'
priority = 0.5

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
[markup.goldmark.parser.attribute]
block = true
title = true


[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10
[[menus.main]]
name = 'People'
pageRef = '/people'
weight = 20
[[menus.main]]
name = 'Research'
pageRef = '/research'
weight = 30
[[menus.main]]
name = 'Publications'
pageRef = '/publications'
weight = 40
[[menus.main]]
name = 'Talks'
pageRef = '/talks'
weight = 45
[[menus.main]]
name = 'Photos'
pageRef = '/photos'
weight = 50
