# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { "https://github.com/yw-choi/yw-choi.github.io" }

gem 'jekyll'

group :jekyll_plugins do
  gem 'jekyll-sitemap'
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
end
